export enum ApiActionCode {
    CREATE = "CREATE",
    READ = "READ",
    READ_ALL = "READ_ALL",
    UPDATE = "UPDATE",
    DELETE = "DELETE",
}


export enum ErrorMessages {
    UNKNOWN_ERROR = "UNKNOWN_ERROR",
    INVALID_ARGUMENT = "INVALID_ARGUMENT",
    NULL_PRIMARY_KEY = "NULL_PRIMARY_KEY",
    UNPERMITTED_OPERATION = "UNPERMITTED_OPERATION",
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
}